### ISSUE TITLE
PruebaNapakalaki.java ,  Dar valores a arrays null

### ISSUE THREAD

**Issue by Nitrosito** [MarFerPra/Napakalaki#1]
Tener cuidado con pasarle un valor "NULL"  al constructor de BadConsequence de tesoros especificos, que a nosotros la profesora en tutoria nos crujio jaja. Dice que debemos pasar un array vacio 

```
new ArrayList()
```

Si probais a buscar por ejemplo monstruos que no hagan perder tesoros especificos, si poneis null al construirlos, explota xDDD

```
for(Monster m : monstruos ){
                 if(m.getBadconsequence().getSpecificHiddenTreasures().isEmpty()==false ||
                    m.getBadconsequence().getSpecificVisibleTreasures().isEmpty()==false){
                     System.out.print(m);
                     System.out.print("\n\n");
                 }
             }
```

**Comment by marco-fp** [comment]
They C me coding, they hating.
